use std::{fs, process::Command};

#[test]
fn numbered_modes_generate_in_author_order_and_check_detects_additions() {
    let root = std::env::temp_dir().join(format!("ascii-mode-generator-{}", std::process::id()));
    fs::create_dir_all(root.join("scripts")).unwrap();
    fs::create_dir_all(root.join("src/modes")).unwrap();
    fs::write(
        root.join("scripts/0_generate_modes.sh"),
        include_str!("../scripts/0_generate_modes.sh"),
    )
    .unwrap();
    for name in [
        "_100_z.rs",
        "_10_b.rs",
        "_2_a.rs",
        "_1a_insert.rs",
        "_1_first.rs",
        "_0_base.rs",
    ] {
        fs::write(root.join("src/modes").join(name), "").unwrap();
    }
    fs::write(root.join("src/modes/mod.rs"), "").unwrap();
    let run = |args: &[&str]| {
        Command::new("bash")
            .arg(root.join("scripts/0_generate_modes.sh"))
            .args(args)
            .output()
            .unwrap()
    };
    assert!(run(&[]).status.success());
    let generated = fs::read_to_string(root.join("src/modes/mod.rs")).unwrap();
    insta::assert_snapshot!(generated, @r#"
    // @generated by scripts/0_generate_modes.sh. Do not edit.

    mod _0_base;
    mod _1_first;
    mod _1a_insert;
    mod _2_a;
    mod _10_b;
    mod _100_z;

    pub(crate) fn register_all(registry: &mut crate::registry::ModeRegistry) {
        registry.add(&_0_base::MODE);
        registry.add(&_1_first::MODE);
        registry.add(&_1a_insert::MODE);
        registry.add(&_2_a::MODE);
        registry.add(&_10_b::MODE);
        registry.add(&_100_z::MODE);
    }
    "#);
    assert!(run(&["--check"]).status.success());
    fs::write(root.join("src/modes/_101_latest.rs"), "").unwrap();
    assert!(!run(&["--check"]).status.success());
    assert_eq!(
        fs::read_to_string(root.join("src/modes/mod.rs")).unwrap(),
        generated
    );
    assert!(run(&[]).status.success());
    assert!(
        fs::read_to_string(root.join("src/modes/mod.rs"))
            .unwrap()
            .contains("registry.add(&_101_latest::MODE);")
    );
    fs::remove_dir_all(root).unwrap();
}
