// @generated by scripts/0_generate_modes.sh. Do not edit.

mod _30_illuminarium;
mod _31_qwen_cathedral;
mod _32_glm_apotheosis;
mod _33_cosmograph;
mod _34_gemini_astrolabe;
mod _35_hyperloom;
mod _36_aetherforge;
mod _37_singularity;
mod _38_thunderhead;
mod _39_mandelbox;
mod _40_moonwake;
mod _41_vesper;

pub(crate) fn register_all(registry: &mut crate::registry::ModeRegistry) {
    registry.add(&_30_illuminarium::MODE);
    registry.add(&_31_qwen_cathedral::MODE);
    registry.add(&_32_glm_apotheosis::MODE);
    registry.add(&_33_cosmograph::MODE);
    registry.add(&_34_gemini_astrolabe::MODE);
    registry.add(&_35_hyperloom::MODE);
    registry.add(&_36_aetherforge::MODE);
    registry.add(&_37_singularity::MODE);
    registry.add(&_38_thunderhead::MODE);
    registry.add(&_39_mandelbox::MODE);
    registry.add(&_40_moonwake::MODE);
    registry.add(&_41_vesper::MODE);
}
