// @generated by scripts/0_generate_modes.sh. Do not edit.

mod _30_illuminarium;
mod _31_qwen_cathedral;
mod _32_glm_apotheosis;
mod _33_cosmograph;
mod _34_gemini_astrolabe;
mod _35_hyperloom;
mod _36_aetherforge;
mod _37_singularity;
mod _38_thunderhead;
mod _39_mandelbox;
mod _40_moonwake;
mod _41_vesper;
mod _42_bower;
mod _43_azulejo;
mod _44_tideglass;
mod _45_chimera_shadow_garden;
mod _46_volute;
mod _47_astra_opus_1_chronofold;
mod _48_astra_jurassic_park;
mod _49_astra_chaos_theory;
mod _50_gem_aetherium_2;
mod _51_terminal_stress;
mod _52_gem_aetherium_3;

#[tracing::instrument(level = "trace", target = "ascii_renderer::functions", skip_all)]
pub(crate) fn register_all(registry: &mut crate::registry::ModeRegistry) {
    registry.add(&_30_illuminarium::MODE);
    registry.add(&_31_qwen_cathedral::MODE);
    registry.add(&_32_glm_apotheosis::MODE);
    registry.add(&_33_cosmograph::MODE);
    registry.add(&_34_gemini_astrolabe::MODE);
    registry.add(&_35_hyperloom::MODE);
    registry.add(&_36_aetherforge::MODE);
    registry.add(&_37_singularity::MODE);
    registry.add(&_38_thunderhead::MODE);
    registry.add(&_39_mandelbox::MODE);
    registry.add(&_40_moonwake::MODE);
    registry.add(&_41_vesper::MODE);
    registry.add(&_42_bower::MODE);
    registry.add(&_43_azulejo::MODE);
    registry.add(&_44_tideglass::MODE);
    registry.add(&_45_chimera_shadow_garden::MODE);
    registry.add(&_46_volute::MODE);
    registry.add(&_47_astra_opus_1_chronofold::MODE);
    registry.add(&_48_astra_jurassic_park::MODE);
    registry.add(&_49_astra_chaos_theory::MODE);
    registry.add(&_50_gem_aetherium_2::MODE);
    registry.add(&_51_terminal_stress::MODE);
    registry.add(&_52_gem_aetherium_3::MODE);
}
