#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(cd "$(dirname "$0")/.." && pwd)
modes_dir="$repo_dir/src/modes"
output="$modes_dir/mod.rs"
mode=${1:-write}

generate() {
    local temporary
    temporary=$(mktemp "$modes_dir/.mod.rs.XXXXXX")
    shopt -s nullglob
    local files=("$modes_dir"/_[0-9]*_*.rs)

    {
        echo '// @generated by scripts/0_generate_modes.sh. Do not edit.'
        echo
        for file in "${files[@]}"; do
            local module
            module=$(basename "$file" .rs)
            echo "mod $module;"
        done
        echo
        echo 'pub(crate) fn register_all(registry: &mut crate::registry::ModeRegistry) {'
        for file in "${files[@]}"; do
            local module
            module=$(basename "$file" .rs)
            echo "    registry.add(&$module::MODE);"
        done
        echo '}'
    } > "$temporary"

    if cmp -s "$temporary" "$output"; then
        rm -f "$temporary"
        return
    fi
    if [[ "$mode" == "--check" ]]; then
        diff -u "$output" "$temporary" || true
        rm -f "$temporary"
        return 1
    fi
    mv -f "$temporary" "$output"
}

if [[ "$mode" == "--watch" ]]; then
    while true; do
        generate
        sleep 0.5
    done
else
    generate
fi
