#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(cd "$(dirname "$0")/.." && pwd)
modes_dir="$repo_dir/src/modes"
output="$modes_dir/mod.rs"
mode=${1:-write}

generate() {
    local temporary
    temporary=$(mktemp "$modes_dir/.mod.rs.XXXXXX")
    shopt -s nullglob
    local discovered=("$modes_dir"/_[0-9]*_*.rs)
    local files=()
    local filename
    # Numeric author order also handles _9_, _10_, and _100_ correctly.
    if (( ${#discovered[@]} )); then
        while IFS= read -r filename; do
            files+=("$modes_dir/$filename")
        done < <(
            for file in "${discovered[@]}"; do
                printf '%s\n' "${file##*/}"
            done | LC_ALL=C sort -t_ -k2,2n -k2,2 -k3
        )
    fi

    {
        echo '// @generated by scripts/0_generate_modes.sh. Do not edit.'
        echo
        for file in "${files[@]}"; do
            local module
            module=$(basename "$file" .rs)
            echo "mod $module;"
        done
        echo
        echo 'pub(crate) fn register_all(registry: &mut crate::registry::ModeRegistry) {'
        for file in "${files[@]}"; do
            local module
            module=$(basename "$file" .rs)
            echo "    registry.add(&$module::MODE);"
        done
        echo '}'
    } > "$temporary"

    if cmp -s "$temporary" "$output"; then
        rm -f "$temporary"
        return
    fi
    if [[ "$mode" == "--check" ]]; then
        diff -u "$output" "$temporary" || true
        rm -f "$temporary"
        return 1
    fi
    mv -f "$temporary" "$output"
}

if [[ "$mode" == "--watch" ]]; then
    while true; do
        generate
        sleep 0.5
    done
else
    generate
fi
