//! Flowers, fruit vines, cloud puffs.
use crate::color::*;
use crate::types::*;
use crossterm::style::Color;
use rand::RngExt;
use rand::rngs::StdRng;
use super::*;

pub fn draw_cloud(
    grid: &mut Grid,
    cx: usize,
    cy: usize,
    cloud_w: usize,
    color: Color,
    rng: &mut StdRng,
) {
    let dense_chars = ['▓', '▒', '░'];
    let wisp_chars = ['░', '·', '∙', '~', '⠂', '⠄'];

    let half_w = (cloud_w / 2) as i32;
    // Generate per-column height profile with random walk
    let mut heights: Vec<i32> = Vec::new();
    let mut h = rng.random_range(1..3u32) as i32;
    for col in 0..cloud_w {
        // Random walk the height: more variation = less blobby
        h += rng.random_range(0..3u32) as i32 - 1;
        h = h.clamp(0, 4);
        // Taper at edges
        let edge_dist = ((col as f32 / cloud_w as f32) - 0.5).abs() * 2.0;
        let taper = ((1.0 - edge_dist * edge_dist) * 3.0) as i32;
        heights.push(h.min(taper).max(0));
    }

    let x0 = cx as i32 - half_w;
    for (col, &col_h) in heights.iter().enumerate() {
        let gx = x0 + col as i32;
        if gx < 0 || gx as usize >= grid[0].len() {
            continue;
        }

        // Dense core: fill from cy - col_h/2 to cy + col_h/2
        let top = cy as i32 - col_h / 2;
        let bot = cy as i32 + (col_h + 1) / 2;
        for gy in top..=bot {
            if gy < 0 || gy as usize >= grid.len() {
                continue;
            }
            let vert_dist = ((gy - cy as i32) as f32 / (col_h as f32 + 1.0).max(1.0)).abs();
            let ch = if vert_dist < 0.3 {
                dense_chars[0]
            } else if vert_dist < 0.7 {
                dense_chars[rng.random_range(0..2u32) as usize]
            } else {
                dense_chars[rng.random_range(1..3u32) as usize]
            };
            let brightness = ((1.0 - vert_dist) * 40.0) as u8;
            let c = lighten(color, brightness);
            let cell = &grid[gy as usize][gx as usize];
            if cell.ch == ' ' || cell.ch == '·' {
                grid[gy as usize][gx as usize] = Cell::new(ch, c);
            }
        }

        // Trailing wisps below (30% of columns, 1-2 chars below)
        if rng.random_range(0..3u32) == 0 {
            let wisp_y = bot + 1;
            if wisp_y >= 0 && (wisp_y as usize) < grid.len() {
                let wch = wisp_chars[rng.random_range(0..wisp_chars.len() as u32) as usize];
                let cell = &grid[wisp_y as usize][gx as usize];
                if cell.ch == ' ' || cell.ch == '·' {
                    grid[wisp_y as usize][gx as usize] = Cell::new(wch, darken(color, 20));
                }
            }
        }
    }
}
/// Algorithmic flower: radial petals generated by loop with variable count,
/// radius, rotation offset, and petal chars. No stamp array.
pub fn grow_flower_spiral(grid: &mut Grid, cx: usize, cy: usize, color: Color, rng: &mut StdRng) {
    let petal_count = rng.random_range(3..9u32);
    let radius = rng.random_range(1..3u32) as f32;
    let rotation = rng.random::<f32>() * std::f32::consts::TAU;
    let petal_chars = ['◆', '◇', '●', '○', '∙', '✦', '✧', '◉'];
    let petal_ch = petal_chars[rng.random_range(0..petal_chars.len() as u32) as usize];
    let center_chars = ['✦', '◉', '●', '✧', '◆', '⬤'];
    let center_ch = center_chars[rng.random_range(0..center_chars.len() as u32) as usize];

    // Center
    if cy < grid.len() && cx < grid[0].len() {
        grid[cy][cx] = Cell::new(center_ch, lighten(color, 40));
    }

    // Petals at even angular spacing with rotation offset
    for i in 0..petal_count {
        let angle = rotation + (i as f32 / petal_count as f32) * std::f32::consts::TAU;
        let px = (cx as f32 + angle.cos() * radius * 1.8) as i32; // aspect correction
        let py = (cy as f32 + angle.sin() * radius) as i32;
        if px >= 0 && py >= 0 && (py as usize) < grid.len() && (px as usize) < grid[0].len() {
            let c = if i % 2 == 0 {
                color
            } else {
                lighten(color, 20)
            };
            grid[py as usize][px as usize] = Cell::new(petal_ch, c);
        }
    }

    // Optional stem below (30% chance)
    if rng.random_range(0..3u32) == 0 {
        let stem_len = rng.random_range(1..4u32) as usize;
        for j in 1..=stem_len {
            let sy = cy + j;
            if sy < grid.len() && cx < grid[0].len() {
                grid[sy][cx] = Cell::new('│', darken(color, 30));
            }
        }
    }
}
/// Algorithmic fruit: random walk vine that drops fruit chars along its path.
/// Produces a short meandering line of connected segments with fruit at bends.
pub fn grow_fruit_vine(grid: &mut Grid, cx: usize, cy: usize, color: Color, rng: &mut StdRng) {
    let vine_len = rng.random_range(3..8u32) as usize;
    let fruit_chars = ['●', '◉', '◆', '•'];
    let fruit_ch = fruit_chars[rng.random_range(0..fruit_chars.len() as u32) as usize];

    let mut x = cx as i32;
    let mut y = cy as i32;
    let vine_color = darken(color, 25);

    for step in 0..vine_len {
        // Place vine segment
        if x >= 0 && y >= 0 && (y as usize) < grid.len() && (x as usize) < grid[0].len() {
            // Every 2-3 steps place a fruit, otherwise vine char
            if step % rng.random_range(2..4u32) as usize == 0 {
                grid[y as usize][x as usize] = Cell::new(fruit_ch, lighten(color, 30));
            } else {
                let vine_ch = match rng.random_range(0..3u32) {
                    0 => '╌',
                    1 => '∿',
                    _ => '~',
                };
                grid[y as usize][x as usize] = Cell::new(vine_ch, vine_color);
            }
        }

        // Random walk: favor horizontal spread, slight vertical
        match rng.random_range(0..5u32) {
            0 => x -= 1,
            1 => x += 1,
            2 => {
                x += 1;
                y += 1;
            }
            3 => {
                x -= 1;
                y += 1;
            }
            _ => {
                x += if rng.random_range(0..2u32) == 0 {
                    -1
                } else {
                    1
                }
            }
        }
    }
}
/// Draw a small flower/rosette at (cx, cy)
pub fn draw_flower(grid: &mut Grid, cx: usize, cy: usize, style: usize, color: Color) {
    let patterns: &[&[(i32, i32, char)]] = &[
        &[
            (0, -1, '◆'),
            (-1, 0, '◇'),
            (1, 0, '◇'),
            (0, 1, '◆'),
            (0, 0, '✦'),
        ],
        &[
            (0, -1, '◠'),
            (-1, 0, '◟'),
            (1, 0, '◞'),
            (0, 1, '◡'),
            (0, 0, '◉'),
        ],
        &[
            (0, -1, '∧'),
            (-1, 0, '⟨'),
            (1, 0, '⟩'),
            (0, 1, '∨'),
            (0, 0, '✧'),
            (-1, -1, '╱'),
            (1, -1, '╲'),
            (-1, 1, '╲'),
            (1, 1, '╱'),
        ],
        &[
            (0, -1, '╥'),
            (-1, 0, '╟'),
            (1, 0, '╢'),
            (0, 1, '╨'),
            (0, 0, '╬'),
            (-1, -1, '╔'),
            (1, -1, '╗'),
            (-1, 1, '╚'),
            (1, 1, '╝'),
        ],
        &[
            (0, 0, '⣿'),
            (-1, 0, '⡇'),
            (1, 0, '⢸'),
            (0, -1, '⣤'),
            (0, 1, '⣶'),
            (-1, -1, '⠁'),
            (1, -1, '⠈'),
            (-1, 1, '⢀'),
            (1, 1, '⡀'),
        ],
    ];

    let pattern = patterns[style % patterns.len()];
    for (i, &(dx, dy, ch)) in pattern.iter().enumerate() {
        let x = cx as i32 + dx;
        let y = cy as i32 + dy;
        if x >= 0 && y >= 0 && (y as usize) < grid.len() && (x as usize) < grid[0].len() {
            let c = if i == pattern.len() - 1 || (dx == 0 && dy == 0) {
                lighten(color, 40)
            } else {
                color
            };
            grid[y as usize][x as usize] = Cell::new(ch, c);
        }
    }
}
